### ISSUE TITLE
bower.json error param 'main'

### ISSUE THREAD

**Issue by ennett50** [asleepwalker/jquery-ui.combobox#1]
If you use webpack and his `require('jquery-ui.combobox')` that you will have error like `Cannot resolve 'file' or 'directory' ./jquery-ui.combobox.js in ~/project/bower_components/jquery-ui.combobox`

This problem will fix if you update your bower.json  rather line

```
"main": "./lib/jquery-ui.combobox.js",
```

Thanks!

**Comment by asleepwalker** [comment]
I did it. Thank you! :)
